#include <iostream>
#include <vector>
#include <fstream>
#include <thread>
#include <boost/filesystem.hpp>
#include <iostream>
#include <exception>
#include <stdexcept>
#include <sstream>
#include <pocketsphinx.h>
#include <thread>
#include <cmath>
#include <string>
#include <tuple>
#include <boost/format.hpp>
#include <random>
#include <thread>
#include <rapidjson/document.h>
#include <iostream>
#include <boost/program_options.hpp>
#include <string>
#include <memory>
#include <map>
#include <boost/network/protocol.hpp>
#include <utility>
#include <algorithm>
#include <exception>
#include <stdexcept>
#include <thread>
#include <deque>
#include <cppconn/prepared_statement.h>
#include <cppconn/statement.h>
#include <cppconn/driver.h>
#include <cppconn/connection.h>
#include <mysql_driver.h>
#include <mysql_connection.h>
#include <memory>

